name: SonarQube Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Download and Run Sonar Scanner without installing system packages
      - name: Download and Run Sonar Scanner
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
          PATH: /usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
        run: |
          # Download portable sonar-scanner binary
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=vimalathanga_git-assignment2 \
            -Dsonar.organization=vimalathanga \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
